### ISSUE TITLE
Words that are supposed to contain "dt" instead have "h2"

### ISSUE THREAD

**Issue by jewellscott** [j9t/web-development-glossary-forum#8]
It seems like a find and replace gone wrong. Can be seen starting on Chapter 4. Do a ctrl+F or cmd+f on Chapter 4, 5, etc for "h2" and you'll see the errors.

**Comment by j9t** [comment]
Hi @jewellscott—thanks for reporting this!

I just checked the source files and also searched the PDF version of the glossary, but I can’t spot any issues there.

Can you share more about the problem, like a screenshot and how/where you are reading the book (format, reader)?

**Comment by jewellscott** [comment]
I'm reading the book on Sitepoint. 

![Bandwidth](https://user-images.githubusercontent.com/15366334/100550885-1ae3ba00-324b-11eb-8f57-b414568319fe.PNG)

![Character Entity Reference](https://user-images.githubusercontent.com/15366334/100550886-1ae3ba00-324b-11eb-9db2-707cc14cb821.PNG)

**Comment by j9t** [comment]
Thank you! I can’t reproduce this anywhere on my end—the EPUB version that SitePoint is working with looks fine, too—but I have let the SitePoint team know and sent them the latest so that they can investigate and fix this. I’ll report back once I know more.

A note, I’d be happy to provide you with your own copy—email me through jens at meiert com and I’ll send you the files.

**Comment by j9t** [comment]
Hi @jewellscott—the SitePoint team got back to me, the issue should be fixed. I looked at this there and it seems fine—can you confirm?

I’m feeling free to close this, then; the offer to get a copy still holds!
